name: 🚀 Build & Deploy
on:
    push:
        branches:
            - master
        paths-ignore:
            - '**/.git*'
            - '**/.git*/**'
            - '**/node_modules/**'
            - '**/.vscode/**'
            - '.editorconfig'
            - '.gitignore'
            - '.prettierignore'
            - '.prettierrc'
            - 'main.js'
            - 'package-lock.json'
            - 'package.json'
            - 'readme.md'
            - 'safelist.txt'
            - 'tailwind.config.js'
            - 'vite.config.js'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install node 20
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install node dependencies
              run: npm install

            - name: Build theme
              run: npm run build

            - name: Upload artifact
              # Persist data produced during the build steps with a retention period of 1 day
              uses: actions/upload-artifact@v4
              with:
                  name: vite-build
                  path: dist/
                  retention-days: 1

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # Fetch the entire Git history
                  fetch-depth: 0

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: vite-build
                  path: .

            - name: Deploy via SFTP
              uses: pressidium/lftp-mirror-action@v1
              with:
                  host: ${{ secrets.SFTP_HOST }}
                  port: ${{ secrets.SFTP_PORT }}
                  user: ${{ secrets.SFTP_USER }}
                  pass: ${{ secrets.SFTP_PASS }}
                  remoteDir: '/wordpress/wp-content/themes/gruyerepadelclub'
                  options: '--verbose'
